language: ruby
services:
  - postgresql
before_install:
  - gem install bundler
matrix:
  include:
    - rvm: 2.5
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_6_0.gemfile
cache:
  - bundler
script: "bundle exec rake"
env:
  - CODECOV_TOKEN="fab4ddb8-ba2c-47cb-a407-941209ad54a4"
